Notification = Error
executable = /users/sista/kkontras/Documents/Epilepsy_Challenge/irregulars_neureka_codebase/condor/script_m.sh
initialdir = /users/sista/kkontras/Documents/Epilepsy_Challenge/irregulars_neureka_codebase/condor/logs
Log = $(ClusterId)_$(Process).log
Output = $(ClusterId)_$(Process).out
Error = $(ClusterId)_$(Process).err
RequestCpus = 8
RequestMemory = 22G
RequestWalltime = 100000
Request_GPUs = 1
NiceUser = True
Requirements = ( GPUs_GlobalMemoryMb > 14500)
Queue Arguments from (
/users/sista/kkontras/Documents/Epilepsy_Challenge/irregulars_neureka_codebase/main.py,config-./configs/neureka_rawwiener.json,default_config-./configs/default_config_tuhsz2.json,rsz-0.5,lr-0.001,wd-0.0001,bs-32
/users/sista/kkontras/Documents/Epilepsy_Challenge/irregulars_neureka_codebase/main.py,config-./configs/neureka_rawwiener.json,default_config-./configs/default_config_tuhsz2.json,rsz-0.5,lr-0.0001,wd-0.0001,bs-32
/users/sista/kkontras/Documents/Epilepsy_Challenge/irregulars_neureka_codebase/main.py,config-./configs/neureka_rawwiener.json,default_config-./configs/default_config_tuhsz2.json,rsz-0.5,lr-0.00001,wd-0.0001,bs-32
)
